### ISSUE TITLE
Linear Conflict Violates Admissiblity

### ISSUE THREAD

**Issue by LukeGarrigan** [jDramaix/SlidingPuzzle#1]
So heuristics violate admissibility if they are pessimistic. So say a puzzle requires 4 moves to get to the goal state but the heuristic says it requires 5.

Linear conflict applies when two tiles are positioned in their desired row or column but are reversed relative to their goal positions, meaning a given tile must move out of the row or column in order to let the other pass.

Say we are focusing on one row which has the configuration [ 3, 1, 2 ]

Let's assume [ 1, 2, 3 ] is the goal configuration.

The summed manhattan distance for the problem is: 4 (3 moves 2 times, 1 moves 1 time and 2 moves 1 time) The linear conflict for the row is: 4 ( 1 and 2 are both less than 3 so +2+2 )

Which results in an overall heuristic estimate of 8. [ 3, 1, 2 ] can be solved in 6 moves

**Comment by jDramaix** [comment]
You either use Manhattan distance or linear conflict as heuristic not the sum of both

**Comment by LukeGarrigan** [comment]
Linear conflict is an extension to improve manhattan distance.

	@Override
	protected int calculate(State s) {
		
		int heuristic = super.calculate(s);
		
		heuristic += linearVerticalConflict(s);
		heuristic += linearHorizontalConflict(s);
		
		return heuristic;

	}

your code follows this, it executes the manhattan distance of the state then adds the linearconflicts to it, thus violates admissibility on some occasions

**Comment by LukeGarrigan** [comment]
Please take a look at the algorithm proposed here https://cse.sc.edu/~mgv/csce580sp15/gradPres/HanssonMayerYung1992.pdf 

Linear conflict is more complex than just adding two each time.

Also your IDA* isn't correct either, the threshold should be determined by the f value, not just incremented by 2.

**Comment by MaximeCheramy** [comment]
> You either use Manhattan distance or linear conflict as heuristic not the sum of both

Your code seems to use the sum of both, which is fine if the linear conflict heuristic is correctly calculated. The article of Hansson et al. gives the following example: [5, 3, 4] (where goal is [3, 4, 5])

> [...] the 5  tile is in conflict with the 3 and the 4. Clearly, either the 5  has to move out of the way (two  extra moves) and allow the others to pass to their goal positions, or the 3 and 4 have to  move and allow the 5  to pass (four extra moves). 

In that case, the linear conflict heuristic should give 2 extra moves (the minimum of the 2 options). However, it looks like your code gives 4 for this particular case.
